algoritmo "calculo"
var
n,d : inteiro
tp : real

inicio

// informe um numero
escreval ("Informe um numero ")
leia (n)

// calcule o dobro desse numero
d <- n*2

// calcule a terça parte desse numero
tp <- n/3

// monstre na tela as informações calculadas
escreval ("O  dobro do seu numero é " ,d)
escreval ("A terça parte do seu numero é " ,tp:2:2)
escreval ("Obrigado")

fimalgoritmo