Algoritmo "SomaDeNumeros"
Var
   numero1, numero2, soma: Inteiro

Inicio
   // Solicita o primeiro número ao usuário
   Escreva("Digite o primeiro número: ")
   Leia(numero1)

   // Solicita o segundo número ao usuário
   Escreva("Digite o segundo número: ")
   Leia(numero2)

   // Calcula a soma
   soma := numero1 + numero2

   // Exibe o resultado
   Escreva("A soma dos números é: ", soma)

FimAlgoritmo
